// docs/examples/react-van/src/App.jsx
import './App.css'
import { VanWrapper } from 'van-wrapper/react'
import van from "vanjs-core"
import Counter from './Counter.js'
const {a, p, div} = van.tags
const Hello = ({message}) => div(
  p(message, a({href: "https://vanjs.org/"}, "VanJS")),
  p(
    "This is a ",
    a({href: "https://vanjs.org/"}, "VanJS "),
    "Element Wrapped inside React App"
  )
)
function App() {
  return (
    <>
    <VanWrapper>
      <Hello message="👋Hello World "/>
      <Counter emoji="❤️" />
      <Counter emoji="✅" />
    </VanWrapper>
    </>
  )
}

export default App

// examples/van-wrapper/src/App.vue
<script setup>
import van from "vanjs-core"
import { VanWrapper } from "van-wrapper/vue";
const {a, p, div} = van.tags
const Hello = ({message}) => div(
  p(message, a({href: "https://vanjs.org/"}, "VanJS")),
  p(
    "This is a ",
    a({href: "https://vanjs.org/"}, "VanJS "),
    "Element Wrapped inside Vue App"
  )
)
</script>

<template>
  <VanWrapper>
    <Hello message="Hello world"/>
  </VanWrapper>
</template>
